# Generated by Django 5.2.17 on 2026-09-23 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


DEFAULT_TEMPLATE_CONTENT = {
    "mau_a": {
        "leftHeader": "ĐOÀN ĐẠI HỌC QUỐC GIA HÀ NỘI\nBCH TRƯỜNG ĐẠI HỌC CÔNG NGHỆ\n***",
        "rightHeader": "ĐOÀN TNCS HỒ CHÍ MINH",
        "title": "ĐƠN ĐỀ NGHỊ",
        "recipient": "Kính gửi: Phòng Hành chính Quản trị và Tổ chức Cán bộ",
        "intro": (
            "Thực hiện nhiệm vụ kế hoạch năm học, đơn vị đăng ký mượn phòng "
            "để tổ chức hoạt động theo danh sách bên dưới."
        ),
        "commitment": (
            "Đơn vị cam kết sử dụng phòng đúng mục đích, giữ gìn cơ sở vật chất "
            "và hoàn trả nguyên trạng sau khi sử dụng."
        ),
        "closing": "Kính mong Quý Phòng xem xét và hỗ trợ. Xin trân trọng cảm ơn!",
        "leftSignature": "Ý KIẾN\nPHÒNG HCQT & TCCB",
        "rightSignature": "TM. BCH ĐOÀN TRƯỜNG\nUV BAN THƯỜNG VỤ",
    },
    "mau_b": {
        "leftHeader": "ĐOÀN ĐẠI HỌC QUỐC GIA HÀ NỘI\nBCH TRƯỜNG ĐẠI HỌC CÔNG NGHỆ\n***",
        "rightHeader": "ĐOÀN TNCS HỒ CHÍ MINH",
        "title": "ĐƠN ĐỀ NGHỊ",
        "recipient": "Kính gửi: Phòng Hành chính Quản trị và Tổ chức Cán bộ",
        "intro": (
            "Văn phòng Đoàn tổng hợp các lịch mượn phòng đã được duyệt "
            "trong khoảng thời gian dưới đây."
        ),
        "commitment": (
            "Các đơn vị trực thuộc ĐTN - HSV cam kết hoàn trả nguyên trạng "
            "cơ sở vật chất sau khi sử dụng."
        ),
        "closing": "Kính mong Quý Phòng xem xét và hỗ trợ. Xin trân trọng cảm ơn!",
        "leftSignature": "Ý KIẾN\nPHÒNG HCQT & TCCB",
        "rightSignature": "TM. BCH ĐOÀN TRƯỜNG\nUV BAN THƯỜNG VỤ",
    },
}


def seed_document_templates(apps, schema_editor):
    document_template = apps.get_model("bookings", "DocumentTemplate")
    for template_type, content in DEFAULT_TEMPLATE_CONTENT.items():
        document_template.objects.update_or_create(
            template_type=template_type,
            defaults={
                "name": "Mẫu A" if template_type == "mau_a" else "Mẫu B",
                "content": content,
                "active": True,
            },
        )


def unseed_document_templates(apps, schema_editor):
    document_template = apps.get_model("bookings", "DocumentTemplate")
    document_template.objects.filter(template_type__in=DEFAULT_TEMPLATE_CONTENT).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_organization_contact_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('mau_a', 'Mẫu A'), ('mau_b', 'Mẫu B')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_document_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['template_type'],
            },
        ),
        migrations.RunPython(seed_document_templates, unseed_document_templates),
    ]
