# Generated by Django 5.2.17 on 2026-09-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_add_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='was_active_before_archive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='was_active_before_archive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='was_active_before_archive',
            field=models.BooleanField(default=True),
        ),
    ]
