# Generated by Django 5.2.17 on 2026-09-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_booking_paper_deadline_at_booking_scan_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='application_group',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
