# Generated by Django 5.2.17 on 2026-09-24 14:45

import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_booking_application_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='prevent_room_double_booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='scan_reupload_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='scan_reupload_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs revision'), ('room_changed', 'Room changed'), ('cancelled', 'Cancelled'), ('physical_reminder', 'Physical reminder'), ('expired', 'Expired'), ('cancel_request', 'Cancel request')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['pending_hold', 'needs_revision', 'approved', 'room_changed']), models.Q(('hold_expires_at__isnull', False), ('status', 'draft')), _connector='OR'), expressions=[('room', '='), ('during', '&&')], name='prevent_room_double_booking'),
        ),
    ]
